#! /bin/bash

# whiptail messages
w_title_one="Compile Debian Based Linux Kernel"
w_msg_one="Welcome. This script is intended to help simplify compiling a Linux Kernel.\n\n"
w_msg_one+="There is no magic here, all the commands are standard and you are \n"
w_msg_one+="encouraged to have a look at the code. Powerusers will likely find this \n"
w_msg_one+="script less than useful as there is some bloat and compilation can be \n"
w_msg_one+="done efficiently at the command line with a few instructions. The target \n"
w_msg_one+="audience here is those less comfortable within a terminal and explains the \n"
w_msg_one+="use of whiptail. Hopefully it will take some of the fear away from first \n"
w_msg_one+="timers. \n\n"
w_msg_one+="In short the script will update and / or install the necessary components \n"
w_msg_one+="to compile a *.deb file set, compile same, and then prompt for installation.\n"
w_msg_one+="The *deb files can then be managed in standard package mangers.\n\n"

w_title_two="Precompiled Package Not Available"
w_msg_two="The kernel for your detected architecture is not currently available.\n"
w_msg_two+="This indicates a problem with Canoncial, the makers of Ubuntu and\n"
w_msg_two+="not on your local system.\n\nIn most cases you should simply try again later.\n\nExiting and cleaning up."