#!/bin/bash

# Ensure root privledges
SUDO=''

if (( $EUID != 0 )); then
	SUDO='sudo'
fi

# Shared variables
NOW=$(date +%h%d_%H-%m-%S)
VERAPPEND=$(date +.%y%m%d)
UPDATENEEDED=0
OS=$(lsb_release -si)
PLUS="${Cyan}[+]${Reg}"
USE_LATEST=0
QT_URL=https://www.qt.io/download-open-source/

# Compile
OUTPUT="kernel_$NOW.tar.xz"
CMP_FLDR="Build_$NOW"

# Precompiled
TMP_FLDR="/tmp"
MINVER=4
FIELD=7


