#!/bin/bash

# Ensure root privledges
SUDO=''

if (( $EUID != 0 )); then
	SUDO='sudo'
fi

# Shared variables
USE_LATEST=0
UPDATENEEDED=0
OS=$(lsb_release -si)
PLUS="${Cyan}[+]${Reg}"
NOW=$(date +%h%d_%H-%m-%S)
VERAPPEND=$(date +.%y%m%d)
BACKTITLE="SCRIPT SOURCE: https://github.com/mtompkins/linux-kernel-utilities"
# To filter out Release Candidates replace "null" with "-rc"
# Revert change to allow RC's. Do not use "" or " ". 
# The variable must be set!
RC_FILTER="-rc"

# Compile
CMP_FLDR="Build_$NOW"
OUTPUT="kernel_$NOW.tar.xz"

# Precompiled
FIELD=7
MINVER=4
TMP_FLDR="/tmp"
